apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchases-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: purchases
  template:
    metadata:
      labels:
        app: purchases
    spec:
      containers:
        - name: purchases
          image: matusie/purchases
          env: 
            - name: NATS_CLUSTER_ID
              value: secondchances
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DB_URI
              value: 'mongodb://purchases-mongo-srv:27017/purchases'
            - name: jwt_key
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt_key
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: purchases-srv
spec:
  selector:
    app: purchases
  type: ClusterIP
  ports:
    - name: purchases
      protocol: TCP
      port: 3000
      targetPort: 3000