name: tests-purchases

on:
  pull_request:
    paths:
      - 'purchases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd purchases && npm install && npm run test:ci
